import { siteImages } from "@/lib/site-content";

// Drive image URLs - VERIFIED via vision analysis
const DRIVE_SPANAC_LAZI = "https://drive.google.com/thumbnail?id=1Z876mMx5VP0VJPfI6ALVNjetA-tQSgL_&sz=w1200"; // spanac in lăzi verzi
const DRIVE_SPANAC_BOL = "https://drive.google.com/thumbnail?id=1wmRoHXlPZx0USs_2Z2GHlUG9_g8Z0KPN&sz=w1200"; // spanac în bol pe câmp
const DRIVE_SPANAC_SOLAR = "https://drive.google.com/thumbnail?id=10wjThrTuKvuUNcV31GcU03aNdkFwNcRs&sz=w1200"; // spanac în solar
const DRIVE_RIDICHI_BASKET = "https://drive.google.com/thumbnail?id=1-xYHSJJO7bC_2WOLZYW-B3pw1nm2_CBA&sz=w1200"; // ridichi multe
const DRIVE_RIDICHI_COS = "https://drive.google.com/thumbnail?id=19UNdaoTRw8qQ0XW9MicQoEFM0zzFfdPz&sz=w1200"; // ridichi în coș
const DRIVE_RIDICHI_CEAPAVERDE = "https://drive.google.com/thumbnail?id=1XoMC4GpaXT9hW64ZHTNnniW0psUJhNOS&sz=w1200"; // ridichi + ceapă verde
const DRIVE_CEAPA_VERDE = "https://drive.google.com/thumbnail?id=1FhlDzpmwVDK3tb4Ti5_5qhQsieXpCXlb&sz=w1200"; // ceapă verde (spring onions)
const DRIVE_ARPAGIC = "https://drive.google.com/thumbnail?id=1NJ_zAcuZnzHNlfeBQ7dFYm3BL59SmdkW&sz=w1200"; // arpagic / ceapă pentru plantat
const DRIVE_USTUROI_ROABA = "https://drive.google.com/thumbnail?id=1vq5shTBwadT1fEEAT3xa5VMpuYLMWmhI&sz=w1200"; // usturoi în roabă cu utilaj
const DRIVE_SALATE_PUNGI = "https://drive.google.com/thumbnail?id=1lLaEXXJB926T8-50tJSZc_dwul5vHrkQ&sz=w1200"; // salate în pungi
const DRIVE_SALATE_LIVRARE = "https://drive.google.com/thumbnail?id=1s2ENApsm4SUSEL7cgmqqeRNkkXa1Clve&sz=w1200"; // salate+ridichi+fasole în pungi (livrare)
const DRIVE_CARTOFI = "https://drive.google.com/thumbnail?id=1Fp5Qgeh-Ci6YCKe7wKzFP2K6UMC-1ldG&sz=w1200"; // cartofi/rizomi în pământ

export const products = [
  // === LEGUME ===
  {
    id: "rosii-gradina",
    name: "Roșii de grădină",
    category: "Legume",
    description: "Roșii proaspete, gustoase, cultivate local fără chimicale agresive. Perfecte pentru salate și conserve.",
    price: 8,
    unit: "lei / kg",
    stock: 24,
    minOrder: 1,
    featured: true,
    season: "Vară - Toamnă",
    image: siteImages.rosii,
    active: true,
  },
  {
    id: "castraveti",
    name: "Castraveți proaspeți",
    category: "Legume",
    description: "Castraveți crocanți, ideali pentru salate și consum zilnic. Cultivați în solarul nostru.",
    price: 5,
    unit: "lei / kg",
    stock: 18,
    minOrder: 1,
    featured: true,
    season: "Primăvară - Vară",
    image: siteImages.castraveti,
    active: true,
  },
  {
    id: "vinete",
    name: "Vinete",
    category: "Legume",
    description: "Vinete proaspete pentru zacuscă, salată sau preparate la grătar.",
    price: 7,
    unit: "lei / kg",
    stock: 20,
    minOrder: 1,
    featured: true,
    season: "Vară - Toamnă",
    image: siteImages.vinete,
    active: true,
  },
  {
    id: "ardei-kapia",
    name: "Ardei kapia",
    category: "Legume",
    description: "Ardei kapia roșii, ideali pentru zacuscă, conserve sau fierți.",
    price: 9,
    unit: "lei / kg",
    stock: 22,
    minOrder: 1,
    featured: true,
    season: "Vară - Toamnă",
    image: siteImages.kapia,
    active: true,
  },
  {
    id: "ardei-gras",
    name: "Ardei gras",
    category: "Legume",
    description: "Ardei gras în culori variate, pentru salate și umpluturi.",
    price: 9,
    unit: "lei / kg",
    stock: 9,
    minOrder: 1,
    featured: true,
    season: "Vară - Toamnă",
    image: siteImages.kapia,
    active: true,
  },
  {
    id: "spanac",
    name: "Spanac",
    category: "Legume",
    description: "Spanac verde, proaspăt cules din solar. Ideal pentru ciorbe și salate.",
    price: 6,
    unit: "lei / legătură",
    stock: 15,
    minOrder: 1,
    featured: true,
    season: "Primăvară",
    image: DRIVE_SPANAC_LAZI,
    active: true,
  },
  {
    id: "usturoi",
    name: "Usturoi",
    category: "Legume",
    description: "Usturoi românesc, aromat, păstrat în condiții naturale.",
    price: 25,
    unit: "lei / kg",
    stock: 12,
    minOrder: 1,
    featured: false,
    season: "Vară - Toamnă",
    image: DRIVE_USTUROI_ROABA,
    active: true,
  },
  {
    id: "ceapa",
    name: "Ceapă",
    category: "Legume",
    description: "Ceapă de grădină, soiuri locale, păstrată corect.",
    price: 4,
    unit: "lei / kg",
    stock: 30,
    minOrder: 1,
    featured: false,
    season: "Vară - Toamnă",
    image: siteImages.ceapa,
    active: true,
  },
  {
    id: "ceapa-verde",
    name: "Ceapă verde",
    category: "Legume",
    description: "Ceapă verde proaspătă, ideală pentru salate și mâncăruri. Legături mari.",
    price: 4,
    unit: "lei / legătură",
    stock: 20,
    minOrder: 1,
    featured: true,
    season: "Primăvară",
    image: DRIVE_CEAPA_VERDE,
    active: true,
  },
  {
    id: "telina",
    name: "Țelină rădăcină",
    category: "Legume",
    description: "Țelină rădăcină, perfectă pentru supă, ciorbă sau salate de iarnă.",
    price: 8,
    unit: "lei / kg",
    stock: 14,
    minOrder: 1,
    featured: false,
    season: "Toamnă - Iarnă",
    image: siteImages.telina,
    active: true,
  },
  {
    id: "morcovi",
    name: "Morcovi",
    category: "Legume",
    description: "Morcovi cultivați local, dulci și aromați. Direct din roabă, proaspăt scoși din grădină.",
    price: 5,
    unit: "lei / kg",
    stock: 35,
    minOrder: 1,
    featured: true,
    season: "Vară - Toamnă",
    image: siteImages.morcovi,
    active: true,
  },
  {
    id: "patrunjel-verde",
    name: "Pătrunjel verde",
    category: "Legume",
    description: "Pătrunjel verde proaspăt cules, legătură generoasă pentru ciorbe și salate.",
    price: 3,
    unit: "lei / legătură",
    stock: 25,
    minOrder: 1,
    featured: false,
    season: "Primăvară - Toamnă",
    image: siteImages.morcoviCuFrunze,
    active: true,
  },
  {
    id: "cartofi",
    name: "Cartofi de țară",
    category: "Legume",
    description: "Cartofi din producție proprie, soiuri locale. Direct din câmp, păstrați natural.",
    price: 4,
    unit: "lei / kg",
    stock: 50,
    minOrder: 2,
    featured: true,
    season: "Toamnă - Iarnă",
    image: DRIVE_CARTOFI,
    active: true,
  },
  {
    id: "ridichi-rosii",
    name: "Ridichi roșii",
    category: "Legume",
    description: "Ridichi roșii proaspete, crocante, perfecte pentru salate de primăvară. Legături mari cu frunze.",
    price: 5,
    unit: "lei / legătură",
    stock: 22,
    minOrder: 1,
    featured: true,
    season: "Primăvară",
    image: DRIVE_RIDICHI_BASKET,
    active: true,
  },
  {
    id: "salata-verde",
    name: "Salată verde",
    category: "Legume",
    description: "Salată verde proaspătă, livrată în pungi individuale. Crocantă și gustoasă.",
    price: 4,
    unit: "lei / pungă",
    stock: 30,
    minOrder: 1,
    featured: true,
    season: "Primăvară - Vară",
    image: DRIVE_SALATE_PUNGI,
    active: true,
  },
  {
    id: "fasole-boabe",
    name: "Fasole boabe uscată",
    category: "Legume",
    description: "Fasole boabe uscate, soiuri tradiționale. Ideală pentru ciorbe și mâncăruri de iarnă.",
    price: 18,
    unit: "lei / kg",
    stock: 25,
    minOrder: 1,
    featured: false,
    season: "Tot anul",
    image: siteImages.legume,
    active: true,
  },

  // === FRUCTE ===
  {
    id: "zmeura",
    name: "Zmeură proaspătă",
    category: "Fructe",
    description: "Zmeură de sezon, aromată și proaspătă, culeasă din plantația noastră.",
    price: 16,
    unit: "lei / caserolă",
    stock: 8,
    minOrder: 1,
    featured: true,
    season: "Vară",
    image: siteImages.zmeura,
    active: true,
  },
  {
    id: "mure",
    name: "Mure proaspete",
    category: "Fructe",
    description: "Mure de sezon, culese cu grijă, dulci și aromate.",
    price: 18,
    unit: "lei / caserolă",
    stock: 10,
    minOrder: 1,
    featured: true,
    season: "Vară",
    image: siteImages.mure,
    active: true,
  },
  {
    id: "capsuni",
    name: "Căpșuni",
    category: "Fructe",
    description: "Căpșuni dulci de grădină, parfumate și bine coapte.",
    price: 20,
    unit: "lei / caserolă",
    stock: 12,
    minOrder: 1,
    featured: true,
    season: "Primăvară - Vară",
    image: siteImages.capsuni,
    active: true,
  },

  // === FLORI ===
  {
    id: "panselute",
    name: "Panseluțe",
    category: "Flori",
    description: "Flori de sezon pentru grădină, balcon sau curte. Culori variate.",
    price: 2,
    unit: "lei / fir",
    stock: 80,
    minOrder: 1,
    featured: false,
    season: "Primăvară - Vară",
    image: siteImages.panselute,
    active: true,
  },
  {
    id: "petunii-colorate",
    name: "Petunii colorate",
    category: "Flori",
    description: "Petunii colorate în ghiveci, perfecte pentru balcon sau terasă. Înfloresc tot sezonul.",
    price: 12,
    unit: "lei / ghiveci",
    stock: 8,
    minOrder: 1,
    featured: true,
    season: "Primăvară - Toamnă",
    image: siteImages.panselute,
    active: true,
  },
  {
    id: "buchet-flori",
    name: "Buchet de flori",
    category: "Flori",
    description: "Buchete realizate manual, cu flori proaspete din solarul nostru.",
    price: 35,
    unit: "lei / buchet",
    stock: 8,
    minOrder: 1,
    featured: true,
    season: "Tot anul",
    image: siteImages.buchet,
    active: true,
  },

  // === RĂSADURI ===
  {
    id: "rasaduri-legume",
    name: "Răsaduri legume",
    category: "Răsaduri",
    description: "Tomate, ardei, castraveți, vinete – răsaduri sănătoase gata de plantat.",
    price: 0.5,
    unit: "lei / bucată",
    stock: 200,
    minOrder: 5,
    featured: true,
    season: "Primăvară",
    image: siteImages.rasad,
    active: true,
  },

  // === PRODUSE ARTIZANALE ===
  {
    id: "sirop-dulceata",
    name: "Sirop și dulceață",
    category: "Produse artizanale",
    description: "Siropuri și dulcețuri preparate în casă din fructele noastre.",
    price: 22,
    unit: "lei / borcan",
    stock: 25,
    minOrder: 1,
    featured: true,
    season: "Tot anul",
    image: siteImages.siropDulceata,
    active: true,
  },
  {
    id: "zacusca",
    name: "Zacuscă de casă",
    category: "Produse artizanale",
    description: "Zacuscă tradițională din vinete, kapia și roșii cultivate local.",
    price: 25,
    unit: "lei / borcan",
    stock: 18,
    minOrder: 1,
    featured: true,
    season: "Tot anul",
    image: siteImages.zacusca,
    active: true,
  },
  {
    id: "dulceata-caise",
    name: "Dulceață de caise",
    category: "Produse artizanale",
    description: "Dulceață de caise preparată în casă, doar cu fructe proaspete și zahăr. Borcan tradițional cu tricolor.",
    price: 28,
    unit: "lei / borcan",
    stock: 14,
    minOrder: 1,
    featured: true,
    season: "Tot anul",
    image: siteImages.dulceataCaise,
    active: true,
  },
  {
    id: "palinca-traditionala",
    name: "Pălincă tradițională",
    category: "Produse artizanale",
    description: "Pălincă tradițională românească din fructe proprii, distilată cu grijă. Sticlă cu tricolor.",
    price: 95,
    unit: "lei / sticlă 500ml",
    stock: 10,
    minOrder: 1,
    featured: true,
    season: "Tot anul",
    image: siteImages.palincaTraditionala,
    active: true,
  },
];

export const productCategories = [
  "Toate",
  "Legume",
  "Fructe",
  "Flori",
  "Răsaduri",
  "Produse artizanale",
];
