import { siteImages } from "@/lib/site-content";

export const products = [
  // LEGUME
  {
    id: "rosii-gradina",
    name: "Roșii de grădină",
    category: "Legume",
    description: "Roșii proaspete, gustoase, cultivate local fără chimicale agresive.",
    price: 8,
    unit: "lei / kg",
    stock: 24,
    minOrder: 1,
    featured: true,
    season: "Primăvară - Vară",
    image: siteImages.rosii,
    active: true,
  },
  {
    id: "castraveti",
    name: "Castraveți proaspeți",
    category: "Legume",
    description: "Castraveți crocanți, ideali pentru salate și consum zilnic.",
    price: 5,
    unit: "lei / kg",
    stock: 18,
    minOrder: 1,
    featured: true,
    season: "Primăvară - Vară",
    image: siteImages.castraveti,
    active: true,
  },
  {
    id: "vinete",
    name: "Vinete",
    category: "Legume",
    description: "Vinete proaspete pentru zacuscă, salată sau preparate la grătar.",
    price: 7,
    unit: "lei / kg",
    stock: 20,
    minOrder: 1,
    featured: true,
    season: "Vară - Toamnă",
    image: siteImages.vinete,
    active: true,
  },
  {
    id: "ardei-kapia",
    name: "Ardei kapia",
    category: "Legume",
    description: "Ardei kapia roșii, ideali pentru zacuscă, conserve sau fierți.",
    price: 9,
    unit: "lei / kg",
    stock: 22,
    minOrder: 1,
    featured: true,
    season: "Vară - Toamnă",
    image: siteImages.kapia,
    active: true,
  },
  {
    id: "spanac",
    name: "Spanăc",
    category: "Legume",
    description: "Spanăc verde, proaspăt cules, ideal pentru ciorbe și salate.",
    price: 6,
    unit: "lei / legătură",
    stock: 15,
    minOrder: 1,
    featured: true,
    season: "Primăvară",
    image: siteImages.spanac,
    active: true,
  },
  {
    id: "usturoi",
    name: "Usturoi",
    category: "Legume",
    description: "Usturoi românesc, aromat, păstrat în condiții naturale.",
    price: 25,
    unit: "lei / kg",
    stock: 12,
    minOrder: 1,
    featured: false,
    season: "Vară - Toamnă",
    image: siteImages.usturoi,
    active: true,
  },
  {
    id: "ceapa",
    name: "Ceapă",
    category: "Legume",
    description: "Ceapă de grădină, soiuri locale, păstrată corect.",
    price: 4,
    unit: "lei / kg",
    stock: 30,
    minOrder: 1,
    featured: false,
    season: "Vară - Toamnă",
    image: siteImages.ceapa,
    active: true,
  },
  {
    id: "ceapa-verde",
    name: "Ceapă verde",
    category: "Legume",
    description: "Ceapă verde proaspătă, ideală pentru salate și mâncăruri.",
    price: 4,
    unit: "lei / legătură",
    stock: 0,
    minOrder: 1,
    featured: false,
    season: "Primăvară",
    image: siteImages.ceapa,
    active: true,
  },
  {
    id: "ardei-gras",
    name: "Ardei gras",
    category: "Legume",
    description: "Ardei gras în culori variate (roșu, galben, verde), pentru salate și umpluturi.",
    price: 9,
    unit: "lei / kg",
    stock: 9,
    minOrder: 1,
    featured: true,
    season: "Vară - Toamnă",
    image: siteImages.kapia,
    active: true,
  },
  {
    id: "telina",
    name: "Țelină",
    category: "Legume",
    description: "Țelină rădăcină, perfectă pentru supă, ciorbă sau salate de iarnă.",
    price: 8,
    unit: "lei / kg",
    stock: 14,
    minOrder: 1,
    featured: false,
    season: "Toamnă - Iarnă",
    image: siteImages.telina,
    active: true,
  },
  {
    id: "morcovi",
    name: "Morcovi",
    category: "Legume",
    description: "Morcovi cultivați local, dulci și aromați. Ideali pentru supă, ciorbă sau salate.",
    price: 5,
    unit: "lei / kg",
    stock: 35,
    minOrder: 1,
    featured: true,
    season: "Vară - Toamnă",
    image: siteImages.morcovi,
    active: true,
  },
  {
    id: "patrunjel-verde",
    name: "Pătrunjel verde",
    category: "Legume",
    description: "Pătrunjel verde proaspăt cules, legătură generoasă pentru ciorbe și salate.",
    price: 3,
    unit: "lei / legătură",
    stock: 25,
    minOrder: 1,
    featured: false,
    season: "Primăvară - Toamnă",
    image: siteImages.morcoviCuFrunze,
    active: true,
  },
  {
    id: "cartofi",
    name: "Cartofi de țară",
    category: "Legume",
    description: "Cartofi din producție proprie, soiuri locale, păstrați în condiții naturale.",
    price: 4,
    unit: "lei / kg",
    stock: 50,
    minOrder: 2,
    featured: false,
    season: "Toamnă - Iarnă",
    image: siteImages.heroMain,
    active: true,
  },
  {
    id: "patrunjel-radacina",
    name: "Pătrunjel rădăcină",
    category: "Legume",
    description: "Pătrunjel rădăcină pentru supă și ciorbă, cu aromă intensă.",
    price: 10,
    unit: "lei / kg",
    stock: 12,
    minOrder: 1,
    featured: false,
    season: "Toamnă - Iarnă",
    image: siteImages.morcoviCuFrunze,
    active: true,
  },

  // FRUCTE
  {
    id: "zmeura",
    name: "Zmeură proaspătă",
    category: "Fructe",
    description: "Fructe de sezon, aromate și proaspete, culese în aceeași zi.",
    price: 16,
    unit: "lei / caserolă",
    stock: 8,
    minOrder: 1,
    featured: true,
    season: "Vară",
    image: siteImages.zmeura,
    active: true,
  },
  {
    id: "mure",
    name: "Mure proaspete",
    category: "Fructe",
    description: "Mure de sezon, culese cu grijă, dulci și aromate.",
    price: 18,
    unit: "lei / caserolă",
    stock: 10,
    minOrder: 1,
    featured: true,
    season: "Vară",
    image: siteImages.mure,
    active: true,
  },
  {
    id: "capsuni",
    name: "Căpșuni",
    category: "Fructe",
    description: "Căpșuni dulci de grădină, parfumate și bine coapte.",
    price: 20,
    unit: "lei / caserolă",
    stock: 12,
    minOrder: 1,
    featured: true,
    season: "Primăvară - Vară",
    image: siteImages.capsuni,
    active: true,
  },

  // FLORI
  {
    id: "panselute",
    name: "Panseluțe",
    category: "Flori",
    description: "Flori de sezon pentru grădină, balcon sau curte. Culori variate.",
    price: 2,
    unit: "lei / fir",
    stock: 80,
    minOrder: 1,
    featured: false,
    season: "Primăvară - Vară",
    image: siteImages.panselute,
    active: true,
  },
  {
    id: "petunii-colorate",
    name: "Petunii colorate",
    category: "Flori",
    description: "Petunii colorate în ghiveci, perfecte pentru balcon sau terasă. Înfloresc tot sezonul.",
    price: 12,
    unit: "lei / ghiveci",
    stock: 8,
    minOrder: 1,
    featured: true,
    season: "Primăvară - Toamnă",
    image: siteImages.panselute,
    active: true,
  },
  {
    id: "buchet-flori",
    name: "Buchet de flori",
    category: "Flori",
    description: "Buchete realizate manual, cu flori proaspete din solarul nostru.",
    price: 35,
    unit: "lei / buchet",
    stock: 8,
    minOrder: 1,
    featured: true,
    season: "Tot anul",
    image: siteImages.buchet,
    active: true,
  },

  // RĂSADURI
  {
    id: "rasaduri-legume",
    name: "Răsaduri legume",
    category: "Răsaduri",
    description: "Tomate, ardei, castraveți, vinete – răsaduri sănătoase gata de plantat.",
    price: 0.5,
    unit: "lei / bucată",
    stock: 200,
    minOrder: 5,
    featured: true,
    season: "Primăvară",
    image: siteImages.rasad,
    active: true,
  },

  // PRODUSE ARTIZANALE
  {
    id: "sirop-dulceata",
    name: "Sirop și dulceață",
    category: "Produse artizanale",
    description: "Siropuri și dulcețuri preparate în casă din fructele noastre.",
    price: 22,
    unit: "lei / borcan",
    stock: 25,
    minOrder: 1,
    featured: true,
    season: "Tot anul",
    image: siteImages.siropDulceata,
    active: true,
  },
  {
    id: "zacusca",
    name: "Zacuscă de casă",
    category: "Produse artizanale",
    description: "Zacuscă tradițională din vinete, kapia și roșii cultivate local.",
    price: 25,
    unit: "lei / borcan",
    stock: 18,
    minOrder: 1,
    featured: true,
    season: "Tot anul",
    image: siteImages.zacusca,
    active: true,
  },
  {
    id: "dulceata-caise",
    name: "Dulceață de caise",
    category: "Produse artizanale",
    description: "Dulceață de caise preparată în casă, doar cu fructe proaspete și zahăr. Borcan tradițional cu tricolor.",
    price: 28,
    unit: "lei / borcan",
    stock: 14,
    minOrder: 1,
    featured: true,
    season: "Tot anul",
    image: siteImages.dulceataCaise,
    active: true,
  },
  {
    id: "palinca-traditionala",
    name: "Pălincă tradițională",
    category: "Produse artizanale",
    description: "Pălincă tradițională românească din fructe proprii, distilată cu grijă. Sticlă cu tricolor.",
    price: 95,
    unit: "lei / sticlă 500ml",
    stock: 10,
    minOrder: 1,
    featured: true,
    season: "Tot anul",
    image: siteImages.palincaTraditionala,
    active: true,
  },
  {
    id: "sirop-fructe",
    name: "Sirop de fructe natural",
    category: "Produse artizanale",
    description: "Sirop natural din fructe (zmeură, mure sau coacăze) preparat artizanal, fără conservanți.",
    price: 30,
    unit: "lei / sticlă",
    stock: 16,
    minOrder: 1,
    featured: false,
    season: "Tot anul",
    image: siteImages.palincaTraditionala,
    active: true,
  },
];

export const productCategories = [
  "Toate",
  "Legume",
  "Fructe",
  "Flori",
  "Răsaduri",
  "Produse artizanale",
];
